name: Default Inputs

on:
  workflow_dispatch

jobs:
  test-default-inputs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Greet the named user
        uses: ./.github/actions/action.yml
        with:
          name: Bob

      - name: Greet the user without a name
        uses: ./.github/actions/action.yml