name: Multi Job Action

on:
  - push

jobs:
  set-env-var:
    name: Set Env Variable
    runs-on: ubuntu-latest
    outputs:
      imageName: ${{ steps.setVar.outputs.imageName }}
    steps:
      - id: setVar
        name: Set Var
        run: |
          echo "imageName=hello" >> $GITHUB_OUTPUT
      - name: Use output var in same job
        run: |
          echo ${{ steps.setVar.outputs.imageName }}

  use-env-var:
    name: Use Env Variable
    runs-on: ubuntu-latest
    needs: set-env-var
    steps:
      - name: Use Var
        run: |
          echo ${{needs.set-env-var.outputs.imageName}}
