name: Deploy new awslogs docker image to all environments
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to use for AWS Logs docker image. Must be unquie."
        type: string
        required: true

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Display input tag
        env:
          TAG: ${{ github.event.inputs.tag }}
        run: |
          echo "Tag: $TAG"
      - name: Test image dependencies
        run: |
          aws --version
          jq --version
          grep --version